version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

  app:
    build: .
    container_name: travel_assistant
    ports:
      - "8501:8501"
    depends_on:
      - qdrant
    env_file:
      - .env
    volumes:
      - .:/app
      - ./policies:/app/policies
    command: >
      poetry run streamlit run travel_assistant/app/app.py
      --server.port=8501
      --server.address=0.0.0.0
